[versions]
agp = "8.13.2"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
core = "1.17.0"
gamesActivity = "4.4.2"
gamesFramePacing = "2.1.3"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
core = { group = "androidx.core", name = "core", version.ref = "core" }
games-activity = { group = "androidx.games", name = "games-activity", version.ref = "gamesActivity" }
games-frame-pacing = { group = "androidx.games", name = "games-frame-pacing", version.ref = "gamesFramePacing" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
